### ISSUE TITLE
nan waarden uit damo hydroobject voor diepte wordt ingelezen en geeft een fout

### ISSUE THREAD

**Issue by stuart-minion** [hhnk-git/legger#45]
Zie eventueel onderstaande. Ik dacht het op te kunnen lossen met een stukje sql. Echter loopt hij dan later weer vast. Zie de foutmelding helemaal onderaan. Misschien is het beter om bij het inlezen de nan waarden er al uit te gooien. 
https://github.com/hhnk-git/legger/pull/44/commits/44a5302d11e47159b59eb47ed8aa921a647b6d61

TypeError: can't multiply sequence by non-int of type 'float' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\legger\views\calculating_profiles.py", line 298, in execute_step2
    profiles = create_theoretical_profiles(self.polder_datasource, opstuw_norm, bv)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\legger\utils\theoretical_profiles.py", line 321, in create_theoretical_profiles
    cat['max_diepte'] * 1.2, last_category, max_depth_settings[cat['categorieoppwaterlichaam']])
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by stuart-minion** [comment]
gaat om polder groot limmer (castricum)
