### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by stuart-minion** [hhnk-git/legger#46]
Foutmelding met data castricum, bij het berekenen van de fit

IndexError: tuple index out of range 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\legger\views\calculating_profiles.py", line 318, in execute_step3
    resultaat = doe_profinprof(con_legger.cursor(), con_legger.cursor())
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\legger\utils\profile_match_a.py", line 505, in doe_profinprof
    prof_in_prof(gemprofshapely, theoprofshapely, aantalstappen, precisie, obdiepte, debug)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\legger\utils\profile_match_a.py", line 298, in prof_in_prof
    waterbreedte_gemeten = profgem.bounds[2] - profgem.bounds[0]
IndexError: tuple index out of range

**Comment by bastiaan-roos** [comment]
er gaat iets mis in profiel 19117, wat een lege geometrie oplevert. Check toegevoegd op geldige geometrie.
fix in ffa46589a41f275dd40b38be31e96ccabfc77d9a
